using System;
using System.Collections.Generic;

namespace ESFA.DC.ReportData.Model
{
    public partial class McaGlaDevolvedOccupancyReport
    {
        public int Id { get; set; }
        public string Year { get; set; }
        public int Return { get; set; }
        public int AcMnth { get; set; }
        public int UKPRN { get; set; }
        public string ProviderName { get; set; }
        public string LearnerReferenceNumber { get; set; }
        public long? UniqueLearnerNumber { get; set; }
        public string FamilyName { get; set; }
        public string GivenNames { get; set; }
        public DateTime? DateOfBirth { get; set; }
        public int Ethnicity { get; set; }
        public string Sex { get; set; }
        public int? LLDDandHealthProblem { get; set; }
        public int? PriorAttainment { get; set; }
        public string PostcodePriorToEnrolment { get; set; }
        public int? PreMergerUKPRN { get; set; }
        public string CampusIdentifier { get; set; }
        public string ProviderSpecifiedLearnerMonitoringA { get; set; }
        public string ProviderSpecifiedLearnerMonitoringB { get; set; }
        public int AimSeqNumber { get; set; }
        public string LearningAimReference { get; set; }
        public string LearningAimTitle { get; set; }
        public string SoftwareSupplierAimIdentifier { get; set; }
        public decimal? ApplicableFundingRateFromESOLHours { get; set; }
        public decimal? ApplicableFundingRate { get; set; }
        public string ApplicableProgrammeWeighting { get; set; }
        public decimal? AimValue { get; set; }
        public string NotionalNVQLevel { get; set; }
        public string EntitlementCategoryLevel2or3 { get; set; }
        public decimal? Tier2SectorSubjectArea { get; set; }
        public string Tier2SectorSubjectAreaName { get; set; }
        public int? FundingModel { get; set; }
        public int? FundingAdjustmentForPriorLearning { get; set; }
        public int? OtherFundingAdjment { get; set; }
        public DateTime? OriginalLearningStartDate { get; set; }
        public DateTime? LearningStartDate { get; set; }
        public DateTime? LearningPlannedEndDate { get; set; }
        public int? CompletionStatus { get; set; }
        public DateTime? LearningActualEndDate { get; set; }
        public int? WithdrawReason { get; set; }
        public int? Outcome { get; set; }
        public int? AdditionalDeliveryHours { get; set; }
        public string LearningStartDatePostcode { get; set; }
        public string LocalAuthorityCode { get; set; }
        public string ApplicableAreaFromSourceOfFunding { get; set; }
        public string LDFAMTypeSourceOfFunding { get; set; }
        public string LDFAMTypeFullOrCoFundingIndicator { get; set; }
        public string LDFAMTypeLearningSupportFundingHighestApplicable { get; set; }
        public DateTime? LDFAMTypeLSFDateAppliesFromEarliest { get; set; }
        public DateTime? LDFAMTypeLSFDateAppliesToLatest { get; set; }
        public string LDFAMTypeLDMA { get; set; }
        public string LDFAMTypeLDMB { get; set; }
        public string LDFAMTypeLDMC { get; set; }
        public string LDFAMTypeLDMD { get; set; }
        public string LDFAMTypeLDME { get; set; }
        public string LDFAMTypeLDMF { get; set; }
        public string LDFAMTypeDAMA { get; set; }
        public string LDFAMTypeDAMB { get; set; }
        public string LDFAMTypeDAMC { get; set; }
        public string LDFAMTypeDAMD { get; set; }
        public string LDFAMTypeDAME { get; set; }
        public string LDFAMTypeDAMF { get; set; }
        public string LDFAMTypeRestartIndicator { get; set; }
        public string LDFAMTypeCommunityLearningProvisionType { get; set; }
        public string LDFAMTypeHHSA { get; set; }
        public string LDFAMTypeHHSB { get; set; }
        public string ProviderSpecifiedDeliveryMonitoringA { get; set; }
        public string ProviderSpecifiedDeliveryMonitoringB { get; set; }
        public string ProviderSpecifiedDeliveryMonitoringC { get; set; }
        public string ProviderSpecifiedDeliveryMonitoringD { get; set; }
        public int? LearnerEmploymentStatus { get; set; }
        public int? ESMTypeEmploymentIntensityIndicator { get; set; }
        public int? ESMTypeBenefitStatusIndicator { get; set; }
        public string FundingLineType { get; set; }
        public DateTime? StartForFundingPurposes { get; set; }
        public int? PlannedNumberOfOnProgrammeInstalments { get; set; }
        public decimal? AchievementElement { get; set; }
        public decimal? AchievementPercentage { get; set; }
        public decimal? NonPublicFundedContribution { get; set; }
        public decimal? CappingFactor { get; set; }
        public int? PartnerUKPRN { get; set; }
        public string PartnerUKPRNName { get; set; }
        public string DeliveryLocationPostcode { get; set; }
        public decimal? AreaUplift { get; set; }
        public decimal? DisadvantageUplift { get; set; }
        public DateTime? DateUsedForUpliftsAndOtherLookups { get; set; }
        public decimal? AugustOnProgrammeEarnedCash { get; set; }
        public decimal? AugustBalancingPaymentEarnedCash { get; set; }
        public decimal? AugustAimAchievementEarnedCash { get; set; }
        public decimal? AugustJobOutcomeEarnedCash { get; set; }
        public decimal? AugustLearningSupportEarnedCash { get; set; }
        public decimal? SeptemberOnProgrammeEarnedCash { get; set; }
        public decimal? SeptemberBalancingPaymentEarnedcash { get; set; }
        public decimal? SeptemberAimAchievementEarnedCash { get; set; }
        public decimal? SeptemberJobOutcomeEarnedCash { get; set; }
        public decimal? SeptemberLearningSupportEarnedCash { get; set; }
        public decimal? OctoberOnProgrammeEarnedCash { get; set; }
        public decimal? OctoberBalancingPaymentEarnedcash { get; set; }
        public decimal? OctoberAimAchievementEarnedCash { get; set; }
        public decimal? OctoberJobOutcomeEarnedCash { get; set; }
        public decimal? OctoberLearningSupportEarnedCash { get; set; }
        public decimal? NovemberOnProgrammeEarnedCash { get; set; }
        public decimal? NovemberBalancingPaymentEarnedcash { get; set; }
        public decimal? NovemberAimAchievementEarnedCash { get; set; }
        public decimal? NovemberJobOutcomeEarnedCash { get; set; }
        public decimal? NovemberLearningSupportEarnedCash { get; set; }
        public decimal? DecemberOnProgrammeEarnedCash { get; set; }
        public decimal? DecemberBalancingPaymentEarnedcash { get; set; }
        public decimal? DecemberAimAchievementEarnedCash { get; set; }
        public decimal? DecemberJobOutcomeEarnedCash { get; set; }
        public decimal? DecemberLearningSupportEarnedCash { get; set; }
        public decimal? JanuaryOnProgrammeEarnedCash { get; set; }
        public decimal? JanuaryBalancingPaymentEarnedcash { get; set; }
        public decimal? JanuaryAimAchievementEarnedCash { get; set; }
        public decimal? JanuaryJobOutcomeEarnedCash { get; set; }
        public decimal? JanuaryLearningSupportEarnedCash { get; set; }
        public decimal? FebruaryOnProgrammeEarnedCash { get; set; }
        public decimal? FebruaryBalancingPaymentEarnedcash { get; set; }
        public decimal? FebruaryAimAchievementEarnedCash { get; set; }
        public decimal? FebruaryJobOutcomeEarnedCash { get; set; }
        public decimal? FebruaryLearningSupportEarnedCash { get; set; }
        public decimal? MarchOnProgrammeEarnedCash { get; set; }
        public decimal? MarchBalancingPaymentEarnedcash { get; set; }
        public decimal? MarchAimAchievementEarnedCash { get; set; }
        public decimal? MarchJobOutcomeEarnedCash { get; set; }
        public decimal? MarchLearningSupportEarnedCash { get; set; }
        public decimal? AprilOnProgrammeEarnedCash { get; set; }
        public decimal? AprilBalancingPaymentEarnedcash { get; set; }
        public decimal? AprilAimAchievementEarnedCash { get; set; }
        public decimal? AprilJobOutcomeEarnedCash { get; set; }
        public decimal? AprilLearningSupportEarnedCash { get; set; }
        public decimal? MayOnProgrammeEarnedCash { get; set; }
        public decimal? MayBalancingPaymentEarnedcash { get; set; }
        public decimal? MayAimAchievementEarnedCash { get; set; }
        public decimal? MayJobOutcomeEarnedCash { get; set; }
        public decimal? MayLearningSupportEarnedCash { get; set; }
        public decimal? JuneOnProgrammeEarnedCash { get; set; }
        public decimal? JuneBalancingPaymentEarnedcash { get; set; }
        public decimal? JuneAimAchievementEarnedCash { get; set; }
        public decimal? JuneJobOutcomeEarnedCash { get; set; }
        public decimal? JuneLearningSupportEarnedCash { get; set; }
        public decimal? JulyOnProgrammeEarnedCash { get; set; }
        public decimal? JulyBalancingPaymentEarnedcash { get; set; }
        public decimal? JulyAimAchievementEarnedCash { get; set; }
        public decimal? JulyJobOutcomeEarnedCash { get; set; }
        public decimal? JulyLearningSupportEarnedCash { get; set; }
        public decimal? TotalOnProgrammeEarnedCash { get; set; }
        public decimal? TotalBalancingPaymentEarnedCash { get; set; }
        public decimal? TotalAimAchievementEarnedCash { get; set; }
        public decimal? TotalJobOutcomeEarnedCash { get; set; }
        public decimal? TotalLearningSupportEarnedCash { get; set; }
        public decimal? TotalEarnedCash { get; set; }
        public string OFFICIALSENSITIVE { get; set; }
        public DateTime? CreatedDateTime { get; set; }
    }
}
