CREATE TABLE [dbo].[AppsMonthlyPayment](
	[Ukprn] [int] NOT NULL,
	[ReturnPeriod] [int] NOT NULL,
	[PaymentLearnerReferenceNumber] [varchar](250) NULL,
	[PaymentUniqueLearnerNumber] [bigint] NULL,
	[LearnerCampusIdentifier] [varchar](max) NULL,
	[ProviderSpecifiedLearnerMonitoringA] [varchar](250) NULL,
	[ProviderSpecifiedLearnerMonitoringB] [varchar](250) NULL,
	[PaymentEarningEventAimSeqNumber] [int] NULL,
	[PaymentLearningAimReference] [varchar](max) NULL,
	[LarsLearningDeliveryLearningAimTitle] [varchar](max) NULL,
	[LearningDeliveryOriginalLearningStartDate] [datetime] NULL,
	[PaymentLearningStartDate] [datetime] NULL,
	[LearningDeliveryLearningPlannedEndDate] [datetime] NULL,
	[LearningDeliveryCompletionStatus] [int] NULL,
	[LearningDeliveryLearningActualEndDate] [datetime] NULL,
	[LearningDeliveryAchievementDate] [datetime] NULL,
	[LearningDeliveryOutcome] [int] NULL,
	[PaymentProgrammeType] [int] NULL,
	[PaymentStandardCode] [int] NULL,
	[PaymentFrameworkCode] [int] NULL,
	[PaymentPathwayCode] [int] NULL,
	[LearningDeliveryAimType] [int] NULL,
	[LearningDeliverySoftwareSupplierAimIdentifier] [varchar](max) NULL,
	[LearningDeliveryFamTypeLearningDeliveryMonitoringA] [varchar](max) NULL,
	[LearningDeliveryFamTypeLearningDeliveryMonitoringB] [varchar](max) NULL,
	[LearningDeliveryFamTypeLearningDeliveryMonitoringC] [varchar](max) NULL,
	[LearningDeliveryFamTypeLearningDeliveryMonitoringD] [varchar](max) NULL,
	[LearningDeliveryFamTypeLearningDeliveryMonitoringE] [varchar](max) NULL,
	[LearningDeliveryFamTypeLearningDeliveryMonitoringF] [varchar](max) NULL,
	[ProviderSpecifiedDeliveryMonitoringA] [varchar](max) NULL,
	[ProviderSpecifiedDeliveryMonitoringB] [varchar](max) NULL,
	[ProviderSpecifiedDeliveryMonitoringC] [varchar](max) NULL,
	[ProviderSpecifiedDeliveryMonitoringD] [varchar](max) NULL,
	[LearningDeliveryEndPointAssessmentOrganisation] [varchar](max) NULL,
	[RulebaseAecLearningDeliveryPlannedNumberOfOnProgrammeInstalmentsForAim] [int] NULL,
	[LearningDeliverySubContractedOrPartnershipUkprn] [int] NULL,
	[PaymentPriceEpisodeIdentifier] [varchar](max) NULL,
	[PaymentPriceEpisodeStartDate] [varchar](max) NULL,
	[RulebaseAecApprenticeshipPriceEpisodePriceEpisodeActualEndDate] [datetime] NULL,
	[FcsContractContractAllocationContractAllocationNumber] [varchar](max) NULL,
	[PaymentFundingLineType] [varchar](max) NULL,
	[PaymentApprenticeshipContractType] [int] NULL,
	[LearnerEmploymentStatusEmployerId] [int] NULL,
	[RulebaseAecApprenticeshipPriceEpisodeAgreementIdentifier] [varchar](max) NULL,
	[LearnerEmploymentStatus] [int] NULL,
	[LearnerEmploymentStatusDate] [datetime] NULL,
	[AugustLevyPayments] [decimal](15, 5) NULL,
	[AugustCoInvestmentPayments] [decimal](15, 5) NULL,
	[AugustCoInvestmentDueFromEmployerPayments] [decimal](15, 5) NULL,
	[AugustEmployerAdditionalPayments] [decimal](15, 5) NULL,
	[AugustProviderAdditionalPayments] [decimal](15, 5) NULL,
	[AugustApprenticeAdditionalPayments] [decimal](15, 5) NULL,
	[AugustEnglishAndMathsPayments] [decimal](15, 5) NULL,
	[AugustLearningSupportDisadvantageAndFrameworkUpliftPayments] [decimal](15, 5) NULL,
	[AugustTotalPayments] [decimal](15, 5) NULL,
	[SeptemberLevyPayments] [decimal](15, 5) NULL,
	[SeptemberCoInvestmentPayments] [decimal](15, 5) NULL,
	[SeptemberCoInvestmentDueFromEmployerPayments] [decimal](15, 5) NULL,
	[SeptemberEmployerAdditionalPayments] [decimal](15, 5) NULL,
	[SeptemberProviderAdditionalPayments] [decimal](15, 5) NULL,
	[SeptemberApprenticeAdditionalPayments] [decimal](15, 5) NULL,
	[SeptemberEnglishAndMathsPayments] [decimal](15, 5) NULL,
	[SeptemberLearningSupportDisadvantageAndFrameworkUpliftPayments] [decimal](15, 5) NULL,
	[SeptemberTotalPayments] [decimal](15, 5) NULL,
	[OctoberLevyPayments] [decimal](15, 5) NULL,
	[OctoberCoInvestmentPayments] [decimal](15, 5) NULL,
	[OctoberCoInvestmentDueFromEmployerPayments] [decimal](15, 5) NULL,
	[OctoberEmployerAdditionalPayments] [decimal](15, 5) NULL,
	[OctoberProviderAdditionalPayments] [decimal](15, 5) NULL,
	[OctoberApprenticeAdditionalPayments] [decimal](15, 5) NULL,
	[OctoberEnglishAndMathsPayments] [decimal](15, 5) NULL,
	[OctoberLearningSupportDisadvantageAndFrameworkUpliftPayments] [decimal](15, 5) NULL,
	[OctoberTotalPayments] [decimal](15, 5) NULL,
	[NovemberLevyPayments] [decimal](15, 5) NULL,
	[NovemberCoInvestmentPayments] [decimal](15, 5) NULL,
	[NovemberCoInvestmentDueFromEmployerPayments] [decimal](15, 5) NULL,
	[NovemberEmployerAdditionalPayments] [decimal](15, 5) NULL,
	[NovemberProviderAdditionalPayments] [decimal](15, 5) NULL,
	[NovemberApprenticeAdditionalPayments] [decimal](15, 5) NULL,
	[NovemberEnglishAndMathsPayments] [decimal](15, 5) NULL,
	[NovemberLearningSupportDisadvantageAndFrameworkUpliftPayments] [decimal](15, 5) NULL,
	[NovemberTotalPayments] [decimal](15, 5) NULL,
	[DecemberLevyPayments] [decimal](15, 5) NULL,
	[DecemberCoInvestmentPayments] [decimal](15, 5) NULL,
	[DecemberCoInvestmentDueFromEmployerPayments] [decimal](15, 5) NULL,
	[DecemberEmployerAdditionalPayments] [decimal](15, 5) NULL,
	[DecemberProviderAdditionalPayments] [decimal](15, 5) NULL,
	[DecemberApprenticeAdditionalPayments] [decimal](15, 5) NULL,
	[DecemberEnglishAndMathsPayments] [decimal](15, 5) NULL,
	[DecemberLearningSupportDisadvantageAndFrameworkUpliftPayments] [decimal](15, 5) NULL,
	[DecemberTotalPayments] [decimal](15, 5) NULL,
	[JanuaryLevyPayments] [decimal](15, 5) NULL,
	[JanuaryCoInvestmentPayments] [decimal](15, 5) NULL,
	[JanuaryCoInvestmentDueFromEmployerPayments] [decimal](15, 5) NULL,
	[JanuaryEmployerAdditionalPayments] [decimal](15, 5) NULL,
	[JanuaryProviderAdditionalPayments] [decimal](15, 5) NULL,
	[JanuaryApprenticeAdditionalPayments] [decimal](15, 5) NULL,
	[JanuaryEnglishAndMathsPayments] [decimal](15, 5) NULL,
	[JanuaryLearningSupportDisadvantageAndFrameworkUpliftPayments] [decimal](15, 5) NULL,
	[JanuaryTotalPayments] [decimal](15, 5) NULL,
	[FebruaryLevyPayments] [decimal](15, 5) NULL,
	[FebruaryCoInvestmentPayments] [decimal](15, 5) NULL,
	[FebruaryCoInvestmentDueFromEmployerPayments] [decimal](15, 5) NULL,
	[FebruaryEmployerAdditionalPayments] [decimal](15, 5) NULL,
	[FebruaryProviderAdditionalPayments] [decimal](15, 5) NULL,
	[FebruaryApprenticeAdditionalPayments] [decimal](15, 5) NULL,
	[FebruaryEnglishAndMathsPayments] [decimal](15, 5) NULL,
	[FebruaryLearningSupportDisadvantageAndFrameworkUpliftPayments] [decimal](15, 5) NULL,
	[FebruaryTotalPayments] [decimal](15, 5) NULL,
	[MarchLevyPayments] [decimal](15, 5) NULL,
	[MarchCoInvestmentPayments] [decimal](15, 5) NULL,
	[MarchCoInvestmentDueFromEmployerPayments] [decimal](15, 5) NULL,
	[MarchEmployerAdditionalPayments] [decimal](15, 5) NULL,
	[MarchProviderAdditionalPayments] [decimal](15, 5) NULL,
	[MarchApprenticeAdditionalPayments] [decimal](15, 5) NULL,
	[MarchEnglishAndMathsPayments] [decimal](15, 5) NULL,
	[MarchLearningSupportDisadvantageAndFrameworkUpliftPayments] [decimal](15, 5) NULL,
	[MarchTotalPayments] [decimal](15, 5) NULL,
	[AprilLevyPayments] [decimal](15, 5) NULL,
	[AprilCoInvestmentPayments] [decimal](15, 5) NULL,
	[AprilCoInvestmentDueFromEmployerPayments] [decimal](15, 5) NULL,
	[AprilEmployerAdditionalPayments] [decimal](15, 5) NULL,
	[AprilProviderAdditionalPayments] [decimal](15, 5) NULL,
	[AprilApprenticeAdditionalPayments] [decimal](15, 5) NULL,
	[AprilEnglishAndMathsPayments] [decimal](15, 5) NULL,
	[AprilLearningSupportDisadvantageAndFrameworkUpliftPayments] [decimal](15, 5) NULL,
	[AprilTotalPayments] [decimal](15, 5) NULL,
	[MayLevyPayments] [decimal](15, 5) NULL,
	[MayCoInvestmentPayments] [decimal](15, 5) NULL,
	[MayCoInvestmentDueFromEmployerPayments] [decimal](15, 5) NULL,
	[MayEmployerAdditionalPayments] [decimal](15, 5) NULL,
	[MayProviderAdditionalPayments] [decimal](15, 5) NULL,
	[MayApprenticeAdditionalPayments] [decimal](15, 5) NULL,
	[MayEnglishAndMathsPayments] [decimal](15, 5) NULL,
	[MayLearningSupportDisadvantageAndFrameworkUpliftPayments] [decimal](15, 5) NULL,
	[MayTotalPayments] [decimal](15, 5) NULL,
	[JuneLevyPayments] [decimal](15, 5) NULL,
	[JuneCoInvestmentPayments] [decimal](15, 5) NULL,
	[JuneCoInvestmentDueFromEmployerPayments] [decimal](15, 5) NULL,
	[JuneEmployerAdditionalPayments] [decimal](15, 5) NULL,
	[JuneProviderAdditionalPayments] [decimal](15, 5) NULL,
	[JuneApprenticeAdditionalPayments] [decimal](15, 5) NULL,
	[JuneEnglishAndMathsPayments] [decimal](15, 5) NULL,
	[JuneLearningSupportDisadvantageAndFrameworkUpliftPayments] [decimal](15, 5) NULL,
	[JuneTotalPayments] [decimal](15, 5) NULL,
	[JulyLevyPayments] [decimal](15, 5) NULL,
	[JulyCoInvestmentPayments] [decimal](15, 5) NULL,
	[JulyCoInvestmentDueFromEmployerPayments] [decimal](15, 5) NULL,
	[JulyEmployerAdditionalPayments] [decimal](15, 5) NULL,
	[JulyProviderAdditionalPayments] [decimal](15, 5) NULL,
	[JulyApprenticeAdditionalPayments] [decimal](15, 5) NULL,
	[JulyEnglishAndMathsPayments] [decimal](15, 5) NULL,
	[JulyLearningSupportDisadvantageAndFrameworkUpliftPayments] [decimal](15, 5) NULL,
	[JulyTotalPayments] [decimal](15, 5) NULL,
	[R13LevyPayments] [decimal](15, 5) NULL,
	[R13CoInvestmentPayments] [decimal](15, 5) NULL,
	[R13CoInvestmentDueFromEmployerPayments] [decimal](15, 5) NULL,
	[R13EmployerAdditionalPayments] [decimal](15, 5) NULL,
	[R13ProviderAdditionalPayments] [decimal](15, 5) NULL,
	[R13ApprenticeAdditionalPayments] [decimal](15, 5) NULL,
	[R13EnglishAndMathsPayments] [decimal](15, 5) NULL,
	[R13LearningSupportDisadvantageAndFrameworkUpliftPayments] [decimal](15, 5) NULL,
	[R13TotalPayments] [decimal](15, 5) NULL,
	[R14LevyPayments] [decimal](15, 5) NULL,
	[R14CoInvestmentPayments] [decimal](15, 5) NULL,
	[R14CoInvestmentDueFromEmployerPayments] [decimal](15, 5) NULL,
	[R14EmployerAdditionalPayments] [decimal](15, 5) NULL,
	[R14ProviderAdditionalPayments] [decimal](15, 5) NULL,
	[R14ApprenticeAdditionalPayments] [decimal](15, 5) NULL,
	[R14EnglishAndMathsPayments] [decimal](15, 5) NULL,
	[R14LearningSupportDisadvantageAndFrameworkUpliftPayments] [decimal](15, 5) NULL,
	[R14TotalPayments] [decimal](15, 5) NULL,
	[TotalLevyPayments] [decimal](15, 5) NULL,
	[TotalCoInvestmentPayments] [decimal](15, 5) NULL,
	[TotalCoInvestmentDueFromEmployerPayments] [decimal](15, 5) NULL,
	[TotalEmployerAdditionalPayments] [decimal](15, 5) NULL,
	[TotalProviderAdditionalPayments] [decimal](15, 5) NULL,
	[TotalApprenticeAdditionalPayments] [decimal](15, 5) NULL,
	[TotalEnglishAndMathsPayments] [decimal](15, 5) NULL,
	[TotalLearningSupportDisadvantageAndFrameworkUpliftPayments] [decimal](15, 5) NULL,
	[TotalPayments] [decimal](15, 5) NULL 
)
GO

CREATE CLUSTERED INDEX [IX_AppsMonthlyPayment_Ukprn_ReturnPeriod] ON [dbo].[AppsMonthlyPayment] ([Ukprn],[ReturnPeriod])
